In [1]:
import numpy as np

In [2]:
l1=[10,20,30,40,50,60,70]
print(l1,type(l1))

[10, 20, 30, 40, 50, 60, 70] <class 'list'>


In [3]:
a=np.array(l1)
print(a,type(a))

[10 20 30 40 50 60 70] <class 'numpy.ndarray'>


In [4]:
t=(10,20,30,40,50)
print(t,type(t))

(10, 20, 30, 40, 50) <class 'tuple'>


In [6]:
a=np.array(t)
print(a,type(a))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [7]:
d1={10:1.2,20:34,30:76,98:20}
print(d1,type(d1))

{10: 1.2, 20: 34, 30: 76, 98: 20} <class 'dict'>


In [8]:
a=np.array(d1)
print(a,type(a))

{10: 1.2, 20: 34, 30: 76, 98: 20} <class 'numpy.ndarray'>


In [20]:
t=(10,20,30,40,50,60)
a=np.array(t)

In [21]:
a

array([10, 20, 30, 40, 50, 60])

In [22]:
a.ndim

1

In [23]:
a.shape

(6,)

In [24]:
a.dtype

dtype('int32')

In [26]:
b=a.reshape(2,3)

In [27]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
b=a.reshape(3,2)
b

array([[10, 20],
       [30, 40],
       [50, 60]])

In [31]:
t1=((10,20),(30,40))
print(t1,type(t1))

((10, 20), (30, 40)) <class 'tuple'>


In [32]:
a=np.array(t1)

In [33]:
a

array([[10, 20],
       [30, 40]])

In [34]:
a.ndim


2

In [35]:
a.shape

(2, 2)

In [36]:
t1=((10,20,30),(30,40,70),(67,27,48),(67,38,29))
print(t1,type(t1))

((10, 20, 30), (30, 40, 70), (67, 27, 48), (67, 38, 29)) <class 'tuple'>


In [39]:
a=np.array(t1)
a

array([[10, 20, 30],
       [30, 40, 70],
       [67, 27, 48],
       [67, 38, 29]])

In [38]:
a.ndim

2

In [40]:
a.shape

(4, 3)

In [41]:
t1=((10,20,30),(30,40,70)),((67,27,48),(67,38,29))
print(t1,type(t1))

(((10, 20, 30), (30, 40, 70)), ((67, 27, 48), (67, 38, 29))) <class 'tuple'>


In [42]:
a=np.array(t1)
a

array([[[10, 20, 30],
        [30, 40, 70]],

       [[67, 27, 48],
        [67, 38, 29]]])

In [43]:
a.ndim

3

In [45]:
a.shape

(2, 2, 3)

In [48]:
b=a.reshape(4,3)
b

array([[10, 20, 30],
       [30, 40, 70],
       [67, 27, 48],
       [67, 38, 29]])

In [49]:
c=a.reshape(3,4)
c

array([[10, 20, 30, 30],
       [40, 70, 67, 27],
       [48, 67, 38, 29]])

In [52]:
d=a.reshape(3,2,2)
d

array([[[10, 20],
        [30, 30]],

       [[40, 70],
        [67, 27]],

       [[48, 67],
        [38, 29]]])

In [53]:
d[0]

array([[10, 20],
       [30, 30]])

In [54]:
d[1]

array([[40, 70],
       [67, 27]])

In [55]:
d[2]

array([[48, 67],
       [38, 29]])

# arange

In [57]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a.ndim

1

In [65]:
a=np.arange(10,23,2)
a

array([10, 12, 14, 16, 18, 20, 22])

In [66]:
a=np.arange(10,22,2)
a

array([10, 12, 14, 16, 18, 20])

In [63]:
a=np.arange(1,10,3)
a

array([1, 4, 7])

In [67]:
a.ndim

1

In [68]:
a.shape

(6,)

In [70]:
b=a.reshape(3,2)
b

array([[10, 12],
       [14, 16],
       [18, 20]])

In [71]:
b.ndim

2

In [72]:
l1=[ [[10,20],[30,40]], [[15,25],[35,45]] ]
a=np.array(l1)
a

array([[[10, 20],
        [30, 40]],

       [[15, 25],
        [35, 45]]])

In [73]:
l1=[ [[10,20],[30,40]], [[15,25],[35,45]] ]
a=np.arange(l1)
a

TypeError: unsupported operand type(s) for -: 'list' and 'int'

# $Zeros()

In [74]:
import numpy as np

In [76]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
a=np.zeros(12,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
a.reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
a.reshape(4,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
a.reshape(6,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [81]:
a.reshape(2,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [83]:
a.reshape(2,3,2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [84]:
a.reshape(2,2,3)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [85]:
import numpy as np

In [86]:
a=np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
a=np.zeros((2,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [91]:
a=np.zeros((2,3,2),dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

$Ones()

In [92]:
import numpy as np

In [93]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
a=np.ones(10,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
a=np.ones((4,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
a.shape=(3,2,2)
a

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [98]:
a=np.ones((4,3,3),dtype=int)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

$Full

In [101]:
a=np.full(3,1)
a


array([1, 1, 1])

In [103]:
a=np.full(3,9)
a

array([9, 9, 9])

In [104]:
a=np.full(6,8)
a

array([8, 8, 8, 8, 8, 8])

In [105]:
a=np.full(6,9)
a

array([9, 9, 9, 9, 9, 9])

In [106]:
a.reshape(2,3)


array([[9, 9, 9],
       [9, 9, 9]])

In [107]:
a=np.full((2,3),6)
a

array([[6, 6, 6],
       [6, 6, 6]])

In [108]:
a.reshape(3,2)

array([[6, 6],
       [6, 6],
       [6, 6]])

In [109]:
a=np.full((3,3,3),7)
a

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

$Identity

In [111]:
a=np.identity(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [112]:
a=np.identity(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [113]:
a=np.identity(6,dtype=int)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

$Numpy.hstack()

In [114]:
a = np.array([1, 2, 3]) 
b=np.array([3,5,6])
np.hstack((a,b))

array([1, 2, 3, 3, 5, 6])

In [115]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[4, 5, 6], [7, 8, 9]])
np.hstack((a,b))

array([[1, 2, 4, 5, 6],
       [3, 4, 7, 8, 9]])

$numpy.vstack()

In [118]:
a = np.array([1, 2, 3]) 
b=np.array([3,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [3, 5, 6]])

In [122]:
c =np.array([[1, 2], [3,4]])
d = np.array([[4, 5], [5,6]])
np.vstack((c,d))

array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])

In [129]:
a = np.array([[1, 2], [3,4]])
b = np.array([[4, 5], [5,6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])

In [133]:
a=np.full((3,3,3),"HYD")
print(a,type(a))



[[['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']]

 [['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']]

 [['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']
  ['HYD' 'HYD' 'HYD']]] <class 'numpy.ndarray'>


In [132]:
a.ndim

3

In [134]:
a.shape

(3, 3, 3)

In [135]:
a=np.full((3,3),"HYD")
print(a,type(a))


[['HYD' 'HYD' 'HYD']
 ['HYD' 'HYD' 'HYD']
 ['HYD' 'HYD' 'HYD']] <class 'numpy.ndarray'>


In [136]:
a=np.full((3,3),fill_value="HYD")
print(a,type(a))

[['HYD' 'HYD' 'HYD']
 ['HYD' 'HYD' 'HYD']
 ['HYD' 'HYD' 'HYD']] <class 'numpy.ndarray'>


In [137]:
a=np.full((3,3),fill_value=8)
print(a,type(a))

[[8 8 8]
 [8 8 8]
 [8 8 8]] <class 'numpy.ndarray'>


In [138]:
a=np.full((2,3,3),fill_value=8)
print(a,type(a))

[[[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]] <class 'numpy.ndarray'>


In [140]:
a=np.full(6,2)
a

array([2, 2, 2, 2, 2, 2])

In [141]:
a.ndim

1

In [143]:
a.shape

(6,)

In [145]:
a=random.randint(10,20)
a

NameError: name 'random' is not defined